/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery  Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sbi

import (
	"github.com/nycu-ucr/gonet/http"

	"github.com/nycu-ucr/gin"
)

func (s *Server) getNfDiscoveryRoutes() []Route {
	return []Route{
		{
			"Index",
			http.MethodGet,
			"/",
			func(c *gin.Context) {
				c.JSON(http.StatusOK, "free5gc")
			},
		},
		{
			"SearchNFInstances",
			http.MethodGet,
			"/nf-instances",
			s.HTTPSearchNFInstances,
		},
	}
}

// SearchNFInstances - Search a collection of NF Instances
func (s *Server) HTTPSearchNFInstances(c *gin.Context) {
	s.Processor().HandleNFDiscoveryRequest(c, c.Request.URL.Query())
}
